# Generated by Django 6.0.3 on 2026-03-12 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục', 'verbose_name_plural': '1. Danh mục sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Danh mục khách hàng', 'verbose_name_plural': '3. Danh mục khách hàng'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Quản lý đơn hàng', 'verbose_name_plural': '5. Quản lý đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Chi tiết đơn hàng', 'verbose_name_plural': '6. Chi tiết đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Quản lý sản phẩm', 'verbose_name_plural': '2. Quản lý sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'verbose_name': 'Quản lý mã giảm giá', 'verbose_name_plural': '4. Quản lý mã giảm giá'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Hình ảnh đính kèm'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Trạng thái (Hiển thị/Ẩn)'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category', verbose_name='Danh mục cha'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Đường dẫn tĩnh (Slug)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên danh mục'),
        ),
    ]
