# Generated by Django 6.0.3 on 2026-03-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('visible', 'Hiển thị'), ('hidden', 'Ẩn'), ('out_of_stock', 'Hết hàng')], default='visible', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
