# Generated by Django 6.0.3 on 2026-05-27 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_scheduledtask_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Bài viết', 'verbose_name_plural': '08. Tin tức & Khuyến mãi'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Giỏ hàng', 'verbose_name_plural': '05. Quản lý Giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục', 'verbose_name_plural': '01. Danh mục sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Khách hàng', 'verbose_name_plural': '04. Danh mục khách hàng'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Kho hàng', 'verbose_name_plural': '03. Quản lý Kho hàng'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Đơn hàng', 'verbose_name_plural': '07. Quản lý đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': '02. Quản lý sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='recommendationlog',
            options={'verbose_name': 'Nhật ký gợi ý', 'verbose_name_plural': '09. Nhật ký AI Gợi ý'},
        ),
        migrations.AlterModelOptions(
            name='scheduledtask',
            options={'verbose_name': 'Tác vụ Tự động', 'verbose_name_plural': '10. Tác vụ tự động'},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'verbose_name': 'Mã giảm giá', 'verbose_name_plural': '06. Quản lý mã giảm giá'},
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Ảnh chi tiết')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Ảnh chi tiết sản phẩm',
                'verbose_name_plural': '02b. Ảnh chi tiết sản phẩm',
            },
        ),
    ]
