# Generated by Django 6.0.3 on 2026-07-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_configure_stock_task_intervals'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Thương hiệu'),
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_car_brands',
            field=models.CharField(blank=True, help_text='Nhập nhiều hãng xe bằng dấu phẩy, ví dụ: Toyota, Honda, Ford.', max_length=255, null=True, verbose_name='Hãng xe tương thích'),
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_car_models',
            field=models.CharField(blank=True, help_text='Nhập nhiều dòng xe bằng dấu phẩy, ví dụ: Vios, City, Ranger.', max_length=255, null=True, verbose_name='Dòng xe tương thích'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hãng sản xuất'),
        ),
    ]
