# Generated by Django 6.0.3 on 2026-07-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_brand_product_compatible_car_brands_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('vehicle', models.CharField(blank=True, max_length=120, null=True, verbose_name='Dòng xe')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Nội dung tư vấn')),
                ('status', models.CharField(choices=[('pending', 'Chờ tư vấn'), ('contacted', 'Đã liên hệ'), ('converted', 'Đã lên đơn'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi yêu cầu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần cập nhật cuối')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='store.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Yêu cầu tư vấn',
                'verbose_name_plural': '11. Yêu cầu tư vấn',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng quan tâm')),
                ('consultation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.consultationrequest', verbose_name='Yêu cầu tư vấn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong yêu cầu tư vấn',
                'verbose_name_plural': 'Sản phẩm trong yêu cầu tư vấn',
                'unique_together': {('consultation_request', 'product')},
            },
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='consultation_requests', through='store.ConsultationRequestItem', to='store.product', verbose_name='Sản phẩm cần tư vấn'),
        ),
    ]
