# Generated by Django 6.0.3 on 2026-07-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_consultationrequest_consultationrequestitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Chờ xử lý'),
                    ('Confirmed', 'Đã lên đơn'),
                    ('Shipping', 'Đang vận chuyển'),
                    ('Shipped', 'Đã giao hàng'),
                    ('Cancelled', 'Đã hủy'),
                ],
                default='Pending',
                max_length=50,
                verbose_name='Trạng thái đơn',
            ),
        ),
    ]
