UPTEK_SAMPLE_PRODUCTS = [
    {
        "category": "Thiết bị lốp & nâng hạ",
        "sku": "UPTEK-XTB820A",
        "name": "Máy cân bằng lốp UPTEK-XTB820A",
        "description": "Máy cân bằng lốp xe con cho garage, hỗ trợ cân bằng bánh xe nhanh, giảm rung lắc vô lăng và tăng độ ổn định khi vận hành.",
        "price": 38500000,
    },
    {
        "category": "Thiết bị lốp & nâng hạ",
        "sku": "UPTEK-U120",
        "name": "Máy ra vào lốp ô tô xe máy UPTEK U-120",
        "description": "Máy ra vào lốp phù hợp xe du lịch và xe máy, hỗ trợ tháo lắp lốp nhanh, dùng cho cửa hàng lốp và trạm chăm sóc xe.",
        "price": 29500000,
    },
    {
        "category": "Thiết bị lốp & nâng hạ",
        "sku": "UPTEK-U226",
        "name": "Máy ra vào lốp xe du lịch UPTEK U-226",
        "description": "Máy tháo vỏ xe du lịch có mâm kẹp chắc, ben bí ép lốp khỏe, giúp garage xử lý lốp nhanh và an toàn.",
        "price": 42800000,
    },
    {
        "category": "Thiết bị lốp & nâng hạ",
        "sku": "UPTEK-LIFT-4000",
        "name": "Cầu nâng 2 trụ giằng trên UPTEK U-4000",
        "description": "Cầu nâng 2 trụ tải trọng 4 tấn cho gara sửa chữa ô tô, hỗ trợ nâng xe ổn định khi bảo dưỡng gầm, phanh và hệ thống treo.",
        "price": 69500000,
    },
    {
        "category": "Thiết bị lốp & nâng hạ",
        "sku": "UPTEK-SCISSOR-3500",
        "name": "Cầu nâng cắt kéo nâng bụng xe UPTEK U-3500",
        "description": "Cầu nâng cắt kéo nâng bụng xe cho khu vực chăm sóc nhanh, tiết kiệm diện tích, phù hợp gara và trung tâm detailing.",
        "price": 82000000,
    },
    {
        "category": "Thiết bị lốp & nâng hạ",
        "sku": "UPTEK-UJ3T",
        "name": "Kích cá sấu thủy lực 3 tấn UPTEK UJ-3T",
        "description": "Kích cá sấu thủy lực 3 tấn, nâng xe nhanh, thân kích chắc chắn, phù hợp sửa chữa lưu động và xưởng dịch vụ.",
        "price": 3650000,
    },
    {
        "category": "Rửa xe, Detailing & Đồng sơn",
        "sku": "UPTEK-WASH-2200",
        "name": "Máy rửa xe cao áp UPTEK U-2200",
        "description": "Máy rửa xe cao áp cho tiệm rửa xe và garage, áp lực ổn định, làm sạch thân vỏ, mâm lốp và khoang gầm.",
        "price": 12600000,
    },
    {
        "category": "Rửa xe, Detailing & Đồng sơn",
        "sku": "UPTEK-BF40",
        "name": "Bình bọt tuyết inox 40 lít UPTEK BF-40",
        "description": "Bình bọt tuyết inox 40 lít tạo bọt mịn, phủ đều thân xe, phù hợp quy trình rửa xe chuyên nghiệp.",
        "price": 2850000,
    },
    {
        "category": "Rửa xe, Detailing & Đồng sơn",
        "sku": "UPTEK-UG01",
        "name": "Súng phun rửa gầm xe UPTEK UG-01",
        "description": "Súng phun rửa gầm xe giúp làm sạch bùn đất, muối đường và vết bẩn ở các vị trí khó tiếp cận dưới gầm.",
        "price": 1680000,
    },
    {
        "category": "Rửa xe, Detailing & Đồng sơn",
        "sku": "UPTEK-OD80",
        "name": "Máy hút dầu thải khí nén UPTEK OD-80",
        "description": "Thiết bị hút dầu thải khí nén dùng cho thay dầu động cơ, có bình chứa lớn và phù hợp quy trình bảo dưỡng nhanh.",
        "price": 7200000,
    },
    {
        "category": "Dung dịch & súc rửa",
        "sku": "UPTEK-HG322",
        "name": "Thiết bị súc rửa bình xăng con HG-322",
        "description": "Thiết bị súc rửa bình xăng con, làm sạch cặn bẩn, hỗ trợ phục hồi độ ổn định của động cơ và hệ thống nạp nhiên liệu.",
        "price": 5300000,
    },
    {
        "category": "Dung dịch & súc rửa",
        "sku": "UPTEK-FI6",
        "name": "Máy súc rửa kim phun xăng UPTEK FI-6",
        "description": "Máy súc rửa kim phun xăng 6 xy lanh, kiểm tra tia phun, vệ sinh kim phun và hỗ trợ chẩn đoán hệ thống nhiên liệu.",
        "price": 15800000,
    },
    {
        "category": "Dung dịch & súc rửa",
        "sku": "UPTEK-CC01",
        "name": "Bộ vệ sinh buồng đốt động cơ UPTEK CC-01",
        "description": "Bộ vệ sinh buồng đốt động cơ, giảm muội than, hỗ trợ động cơ tăng tốc mượt và tiết kiệm nhiên liệu hơn.",
        "price": 2450000,
    },
    {
        "category": "Dung dịch & súc rửa",
        "sku": "UPTEK-INJECTOR-CLEAN",
        "name": "Dung dịch vệ sinh kim phun xăng UPTEK Injector Clean",
        "description": "Dung dịch vệ sinh kim phun và buồng đốt, phù hợp bảo dưỡng định kỳ cho xe xăng, giúp cải thiện độ nhạy chân ga.",
        "price": 280000,
    },
    {
        "category": "Dụng cụ sửa chữa Garage",
        "sku": "CSPS-W1212RD",
        "name": "Tủ dụng cụ 3 ngăn CSPS 137cm W1212RD",
        "description": "Tủ dụng cụ 3 ngăn CSPS kích thước 137cm, lưu trữ dụng cụ sửa chữa gọn gàng, phù hợp showroom và xưởng dịch vụ.",
        "price": 9800000,
    },
    {
        "category": "Dụng cụ sửa chữa Garage",
        "sku": "UPTEK-TC7D",
        "name": "Xe đẩy dụng cụ 7 ngăn UPTEK TC-7D",
        "description": "Xe đẩy dụng cụ 7 ngăn có khóa, bánh xe linh hoạt, giúp kỹ thuật viên sắp xếp thiết bị sửa chữa rõ ràng.",
        "price": 7600000,
    },
    {
        "category": "Dụng cụ sửa chữa Garage",
        "sku": "UPTEK-ST108",
        "name": "Bộ khẩu tay vặn 108 chi tiết UPTEK ST-108",
        "description": "Bộ khẩu tay vặn 108 chi tiết gồm tuýp, cần siết, đầu bit và phụ kiện, phù hợp sửa chữa cơ khí ô tô hằng ngày.",
        "price": 2350000,
    },
    {
        "category": "Dụng cụ sửa chữa Garage",
        "sku": "UPTEK-TW200",
        "name": "Cờ lê lực 1/2 inch UPTEK TW-200",
        "description": "Cờ lê lực 1/2 inch dùng để siết bu lông đúng thông số, cần thiết cho bánh xe, gầm máy và chi tiết động cơ.",
        "price": 1850000,
    },
    {
        "category": "Dụng cụ sửa chữa Garage",
        "sku": "UPTEK-IW1200",
        "name": "Súng xiết bu lông khí nén 1/2 inch UPTEK IW-1200",
        "description": "Súng xiết bu lông khí nén lực mở mạnh, tháo lắp bu lông bánh xe nhanh, phù hợp tiệm lốp và garage chuyên nghiệp.",
        "price": 3250000,
    },
    {
        "category": "Dụng cụ sửa chữa Garage",
        "sku": "UPTEK-AR15",
        "name": "Cuộn dây hơi tự rút 15m UPTEK AR-15",
        "description": "Cuộn dây hơi tự rút dài 15m, giúp khu vực làm việc gọn gàng, cấp khí nén ổn định cho súng hơi và dụng cụ khí nén.",
        "price": 2150000,
    },
    {
        "category": "Dụng cụ sửa chữa Garage",
        "sku": "UPTEK-AC50",
        "name": "Máy nén khí không dầu 50 lít UPTEK AC-50",
        "description": "Máy nén khí không dầu 50 lít vận hành êm, cung cấp khí nén cho bơm lốp, vệ sinh nội thất và các dụng cụ hơi nhẹ.",
        "price": 6900000,
    },
    {
        "category": "Dụng cụ sửa chữa Garage",
        "sku": "UPTEK-AF02",
        "name": "Bộ lọc tách nước khí nén UPTEK AF-02",
        "description": "Bộ lọc tách nước khí nén giúp bảo vệ dụng cụ hơi, ổn định áp suất và giảm ẩm trong đường khí.",
        "price": 780000,
    },
    {
        "category": "Rửa xe, Detailing & Đồng sơn",
        "sku": "UPTEK-IR3",
        "name": "Đèn sấy sơn hồng ngoại 3 bóng UPTEK IR-3",
        "description": "Đèn sấy sơn hồng ngoại 3 bóng giúp làm khô sơn nhanh, điều chỉnh vùng sấy linh hoạt cho xưởng đồng sơn ô tô.",
        "price": 14500000,
    },
    {
        "category": "Rửa xe, Detailing & Đồng sơn",
        "sku": "UPTEK-SG600",
        "name": "Súng phun sơn ô tô HVLP UPTEK SG-600",
        "description": "Súng phun sơn HVLP cho bề mặt sơn mịn, tiết kiệm vật liệu, phù hợp sơn dặm, sơn lót và sơn hoàn thiện.",
        "price": 2150000,
    },
    {
        "category": "Rửa xe, Detailing & Đồng sơn",
        "sku": "UPTEK-DA15",
        "name": "Máy đánh bóng đồng tâm UPTEK DA-15",
        "description": "Máy đánh bóng đồng tâm hành trình 15mm, hỗ trợ xóa xước nhẹ, hiệu chỉnh bề mặt sơn và chăm sóc detailing.",
        "price": 4200000,
    },
    {
        "category": "Rửa xe, Detailing & Đồng sơn",
        "sku": "UPTEK-VC30",
        "name": "Máy hút bụi nội thất ô tô 30 lít UPTEK VC-30",
        "description": "Máy hút bụi nội thất ô tô 30 lít, lực hút mạnh, phù hợp vệ sinh ghế, sàn xe và khoang hành lý.",
        "price": 3600000,
    },
    {
        "category": "Rửa xe, Detailing & Đồng sơn",
        "sku": "UPTEK-OZ10",
        "name": "Máy tạo ozone khử mùi nội thất UPTEK OZ-10",
        "description": "Máy tạo ozone khử mùi nội thất, hỗ trợ xử lý mùi ẩm, mùi thuốc lá và mùi điều hòa trong khoang lái.",
        "price": 2950000,
    },
    {
        "category": "Dụng cụ sửa chữa Garage",
        "sku": "UPTEK-BT12",
        "name": "Bộ kiểm tra ắc quy và máy phát UPTEK BT-12",
        "description": "Bộ kiểm tra ắc quy và máy phát, đo điện áp sạc, đánh giá tình trạng bình và hỗ trợ chẩn đoán hệ thống điện xe.",
        "price": 1650000,
    },
    {
        "category": "Dụng cụ sửa chữa Garage",
        "sku": "UPTEK-OBD500",
        "name": "Máy chẩn đoán lỗi OBD2 đa năng UPTEK OBD-500",
        "description": "Máy chẩn đoán lỗi OBD2 đa năng, đọc xóa mã lỗi, xem dữ liệu động và hỗ trợ kiểm tra động cơ nhanh.",
        "price": 5450000,
    },
    {
        "category": "Dụng cụ sửa chữa Garage",
        "sku": "UPTEK-VS55",
        "name": "Camera nội soi động cơ UPTEK VS-5.5",
        "description": "Camera nội soi động cơ màn hình 5.5 inch, kiểm tra buồng đốt, đường ống và vị trí hẹp trong khoang máy.",
        "price": 2850000,
    },
    {
        "category": "Dụng cụ sửa chữa Garage",
        "sku": "UPTEK-BR21",
        "name": "Bộ cảo rotuyn và vam tháo vòng bi UPTEK BR-21",
        "description": "Bộ cảo rotuyn và vam tháo vòng bi dùng cho hệ thống treo, moay ơ, rotuyn và các chi tiết cơ khí gầm xe.",
        "price": 3350000,
    },
]


UPTEK_CATEGORY_DESCRIPTIONS = {
    "Thiết bị lốp & nâng hạ": "Nhóm máy ra vào lốp, máy cân bằng lốp, cầu nâng và kích nâng cho garage.",
    "Rửa xe, Detailing & Đồng sơn": "Thiết bị rửa xe, chăm sóc nội thất, đánh bóng, phun sơn và sấy sơn ô tô.",
    "Dung dịch & súc rửa": "Thiết bị và hóa chất vệ sinh kim phun, buồng đốt, bình xăng con và hệ thống nhiên liệu.",
    "Dụng cụ sửa chữa Garage": "Dụng cụ cơ khí, dụng cụ hơi, tủ đồ nghề, máy chẩn đoán và thiết bị hỗ trợ sửa chữa.",
}
