"""
Django settings for etek_core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from django.utils.translation import gettext_lazy as _
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_local_env():
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_local_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-dev-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv(
    'DJANGO_ALLOWED_HOSTS',
    '127.0.0.1,localhost,testserver',
).split(',')


# Application definition

INSTALLED_APPS = [
    'import_export',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'etek_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'etek_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'etek_db'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'vi'

# Danh sách ngôn ngữ cho phép
LANGUAGES = [
    ('vi', _('Vietnamese')),
    ('en', _('English')),
]

USE_I18N = True

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

JAZZMIN_SETTINGS = {
    "site_title": "ETEK Admin",
    "site_header": "E-Tân Phát",
    "site_brand": "ETEK Dashboard",
    "welcome_sign": "Chào mừng đến với hệ thống quản trị E-Tân Phát ETEK",
    
    # Bật nút chọn ngôn ngữ ở góc trên cùng bên phải
    "language_chooser": True, 
    
    # Bật nút "UI Builder" để bạn tự do phối màu trực tiếp trên web
    "show_ui_builder": False, 
    
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "store.Category": "fas fa-layer-group",
        "store.Product": "fas fa-box-open",
        "store.Customer": "fas fa-user-tag",
        "store.Order": "fas fa-shopping-cart",
        "store.OrderItem": "fas fa-receipt",
        "store.Voucher": "fas fa-ticket-alt",
    },
    # Biểu tượng mặc định nếu quên chưa set icon
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    
    "custom_css": "css/admin_tweaks.css",
    "custom_js": "js/admin_tweaks.js",
}

# TÙY CHỈNH GIAO DIỆN (THEME) JAZZMIN
JAZZMIN_UI_TWEAKS = {
    "theme": "flatly", # Giao diện hiện đại, tối giản và sạch sẽ
    "dark_mode_theme": "darkly", # Giao diện khi bật chế độ ban đêm
    
    "sidebar_nav_flat_style": True,        # Bật kiểu menu phẳng (hiện đại, không có viền nổi)
    "sidebar_nav_child_indent": True,      # Bật thụt lề cho menu con dễ nhìn
    "sidebar_nav_compact_style": False,    # Tắt kiểu nén (để các mục có khoảng không thở)
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
